export const DirectoryType = {
  TOGGLE_CATEGORY_HIDDEN: "TOGGLE_CATEGORY_HIDDEN",
  TOGGLE_STATUS_HIDDEN: "TOGGLE_STATUS_HIDDEN",
  TOGGLE_MOST_VIEW_HIDDEN: "TOGGLE_MOST_VIEW_HIDDEN",
  TOGGLE_MOST_COMMENT_HIDDEN: "TOGGLE_MOST_COMMENT_HIDDEN",
  TOGGLE_YEAR_HIDDEN: "TOGGLE_YEAR_HIDDEN",
  TOGGLE_TV_MOVIE_HIDDEN: "TOGGLE_TV_MOVIE_HIDDEN",
  TOGGLE_DIRECTORY_HIDDEN: "TOGGLE_ALL_HIDDEN",
};
