export const SearchType = {
  TOGGLE_SEARCH_HIDDEN: "TOGGLE_SEARCH_HIDDEN",
  SHOW_DROP_DOWN: "SHOW_DROP_DOWN",
  // DROP_DOWN_START: "DROP_DOWN_START",
  // DROP_DOWN_SUCCESS: "DROP_DOWN_SUCCESS",
  // DROP_DOWN_FAILURE: "DROP_DOWN_FAILURE",
};
