export const TrackingTypes={
    GET_USER_GALLERY_START:"GET_USER_GALLERY_START",
    GET_USER_GALLERY_SUCCESS:"GET_USER_GALLERY_SUCCESS",
    GET_USER_GALLERY_FAILURE:"GET_USER_GALLERY_FAILURE",
    ADD_ITEM_TO_GALLERY:"ADD_ITEM_TO_GALLERY",
    REMOVE_ITEM_FROM_GALLERY:"REMOVE_ITEM_FROM_GALLERY",

}