export const TrackingTypes={
    GET_USER_TRACKING_START:"GET_USER_TRACKING_START",
    GET_USER_TRACKING_SUCCESS:"GET_USER_TRACKING_SUCCESS",
    GET_USER_TRACKING_FAILURE:"GET_USER_TRACKING_FAILURE",
    ADD_ITEM:"ADD_ITEM",
    REMOVE_ITEM:"REMOVE_ITEM",
    CLEAR_ALL:"CLEAR_ALL",
}