export const ItemType = {
    FETCH_ITEM_START:"FETCH_ITEM_START",
    FETCH_ITEM_SUCCESS:"FETCH_ITEM_SUCCESS",
    FETCH_ITEM_FAILURE:"FETCH_ITEM_FAILURE",
    CHECK_ITEM_IN_GALLERY_START:"CHECK_ITEM_IN_GALLERY_START",
    CHECK_ITEM_IN_GALLERY_SUCCESS:"CHECK_ITEM_IN_GALLERY_SUCCESS",
    CHECK_ITEM_IN_GALLERY_FAILURE:"CHECK_ITEM_IN_GALLERY_FAILURE",
};
